// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint: 'https://t22ual57bnfthmsiekua3orimm.appsync-api.ap-south-1.amazonaws.com/graphql',
      region: 'ap-south-1',
      // Backend is configured with Cognito User Pool auth mode.
      // We still pass authToken manually from react-oidc-context.
      defaultAuthMode: 'userPool' as const,
    }
  }
};

export default config;
